language: node_js

os:
  - linux
  - osx

node_js:
  - '8'

git:
  depth: 1

branches:
  only:
  - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
  - export PATH=$HOME/.yarn/bin:$PATH
  - node --version && yarn --version && python --version

install:
  - yarn