shallow_clone: true

environment:
  matrix:
    - nodejs_version: "8"

branches:
  only:
  - master

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - ps: npm install --global --production windows-build-tools

build_script:
  - yarn